### ISSUE TITLE
Variable $VAR_WCS_DESCRIBE_COVERAGE_HTTP_POST_URL has not been declared in Test wcs1-0-0:getcoverage_operations-getcoverage_request-grid_size-get-xml-2

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs10#15]
Test wcs1-0-0:getcoverage_operations-getcoverage_request-grid_size-get-xml-2

Assertion:  When a GetCoverage request is made without a specific grid size and without a grid resolution, the server returns service exception.

Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 40 on line 55 in {...ESCRIBE_COVERAGE_HTTP_POST_...}:

Variable $VAR_WCS_DESCRIBE_COVERAGE_HTTP_POST_URL has not been declared; SystemID: file:/srv/local/teamengine-prod/TE_BASE/work/srv_local_teamengine-prod_TE_BASE_scripts_wcs_1.0.0_ctl_/wcs/wcs1-0-0$getcoverage_operations-getcoverage_request-grid_size-get-xml-2.test; Line#: 55; Column#: -1

Failed to compile stylesheet. 1 error detected.
Result: Failed

**Comment by dstenger** [comment]
Is fixed on following branch: https://github.com/lat-lon/ets-wcs10/tree/getcoverage_operations-getcoverage_request-grid_size-get-xml-2-XPathFailure-2936

Testing is still ongoing.

**Comment by bermud** [comment]
We need a WCS 1.0 server to test the fix before we merge it.

**Comment by dstenger** [comment]
I have tested the fix with a provided test server.
Now, the above documented error does not occur any more, but the test is still failing as no Content-Type is returned by response.
```
   Response from parser parsers:HeadersParser:
      <headers>
   <header>
      <value>HTTP/1.1 504 GATEWAY_TIMEOUT</value>
   </header>
   <header>
      <name>Content-Length</name>
      <value>0</value>
   </header>
   <header>
      <name>Connection</name>
      <value>keep-alive</value>
   </header>
   <!--Response received in [59998] milliseconds--></headers>

Message d1e10621_1:
   [FAIL] Expected XML entity (ServiceExceptionReport) in response, but Content-Type is ''.
```

Further, if [1] is used for testing, the test run is aborted and the WebBrowser returns a 500:
```
HTTP Status 500 - javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 107; columnNumber: 32; An invalid XML character (Unicode: 0x8) was found in the element content of the document.
```

[1] http://ows.eox.at/cite/mapserver?service=wcs&version=1.0.0&request=getcapabilities

**Comment by dstenger** [comment]
Next steps:
* Create a new issue of "HTTP Status 500" error.
* I tested the fix with another server and it works (same failure as reported before, but now the error message can be understood).

**Comment by dstenger** [comment]
A fix for this issue was created and a pull request opened:  #16

**Comment by dstenger** [comment]
As soon as the PR (#16) is merged a new bug will be created for the above discussed error ("HTTP Status 500").

**Comment by dstenger** [comment]
Feature branch was tested successfully and merged into master branch.
The fix will be part of the upcoming release.
