### ISSUE TITLE
Question regarding Test getcoverage_operations-getcoverage_response-multifile_payloads

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs10#17]
Can you please elaborate what does this test case stands for or what does multifile_payload mean? Is this test case optional?

Test service: http://122.15.218.129:8081/OGC_WCS/OGCReqResDispatcher?service=wcs&request=GetCapabilities&version=1.0.0

**Comment by lgoltz** [comment]
Multi-file payloads are explained in chapter 9.3.3 of the WCS 1.0.0 specification [1]:

> Several well-known coverage formats encode data and metadata into multiple files.
> When returning a multi-file payload to the client, WCS 1.0.0 servers should use multi-
> part MIME encoding [IETF RFC 2045].
> 
> NOTE
> A multi-part MIME bundle provides no guidance to clients as to the role of each file: the cli-
> ent must be able to recognize each piece by its MIME type or suggested filename. Other methods for bundling files exist, such as SOAP XML messages with binary attachments; but these will require additional consensus across the OGC suite of specifications.

The explanation are also part of the start page of the ETS. The user can enter a comma separated list of file formats (by default image/tif). If the list is empty the test should not be executed.

[1]  http://www.opengeospatial.org/standards/wcs

**Comment by dstenger** [comment]
Does this definition resolve the problem?
If there are still any open questions, please reopen this issue.
