### ISSUE TITLE
Question regarding Post option

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs10#18]
Team engine also executes test case in Post-KVP as well as Post_XML when Post option is selected. Is there any method in team engine so that we can enable only Post-XML test cases and not POST-KVP?

Test service: http://122.15.218.129:8081/OGC_WCS/OGCReqResDispatcher?service=wcs&request=GetCapabilities&version=1.0.0

**Comment by lgoltz** [comment]
Currently it is not possible to deactivate the tests for POST KVP.  KVP is selected always. 

From wcs.xml:
`<xsl:variable name="kvp" select="true()"/>`

**Comment by dstenger** [comment]
Please reopen this issue, if there are further questions.
