### ISSUE TITLE
Missing references of additional test cases

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs10#21]
We have come across few test cases after executing TeamEngine which are not listed either in WCS Abstract Test Suite page (http://cite.opengeospatial.org/teamengine/about/wcs/1.0.0/site/) and Test Requirements and Assertions page (http://cite.opengeospatial.org/teamengine/about/wcs/1.0.0/site/testreq.html). Where can we find reference to such additional test cases which are apart from above mentioned pages?

a. Test wcs1-0-0:describecoverage_operations-describecoverage_response-supportedcrss-rectifiedgrid
b. Test wcs1-0-0:describecoverage_operations-describecoverage_response-supported_interpolations
c. Test wcs1-0-0:getcapabilities_operations-getcapabilities_request-sections
d. Test wcs1-0-0:getcapabilities_operations-getcapabilities_request-sections
e. Test wcs1-0-0:getcapabilities_operations-getcapabilities_request-sections

**Comment by lgoltz** [comment]
The tests are also missing in the ATS http://cite.opengeospatial.org/teamengine/about/wcs/1.0.0/site/wcs-1.0.0-ats.html

**Comment by keshav-nangare** [comment]
Fixed with #52 PR.
