### ISSUE TITLE
Rename test getcoverage_operations-getcoverage_request-grid_size-get-xml-2

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs10#24]
to getcoverage_operations-getcoverage_request-grid_size-post-xml-2

**Comment by dstenger** [comment]
Issue was fixed by #25.
When testing is completed, the pull request will be merged into master branch.

**Comment by dstenger** [comment]
Fix was successfully tested and merged into master branch. It will be part of the upcoming release.
