### ISSUE TITLE
Update CTL with better information about conformance classes

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-wcs10#27]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
From the [specification](https://portal.opengeospatial.org/files/05-076):

```
2 Conformance     
Conformance with this OGC Implementation Specification may be checked using all the 
relevant tests specified in Annex C (normative).  
```

Test are all grouped under the main test.
