### ISSUE TITLE
getcoverage_operations-getcoverage_request-grid_size-post-xml-2 fails as concat() cannot be executed

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs10#40]
## Setup
SUT: please contact me
Tested locally with beta environment: 
 * http://cite.opengeospatial.org/te2/

## Testfailure
" A sequence of more than one item is not allowed as the first argument of concat()"
 * Failing assertion: https://github.com/opengeospatial/ets-wcs10/blob/4ba964dd70727c62c1482e9149ed3e95196474ef/src/main/scripts/ctl/wcs.xml#L5706-L5709

**Comment by keshav-nangare** [comment]
Fixed with PR #40.

**Comment by dstenger** [comment]
Manual test was successful: Test `getcoverage_operations-getcoverage_request-grid_size-post-xml-2` is passing now.
