### ISSUE TITLE
Incorrect validation of lonLatEnvelope srsName attribute

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs10#44]
When testing the WCS 1.0.0 service at:

https://demo.cubewerx.com/cubewerx/cubeserv/simple?DATASTORE=Foundation&SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.0.0

the wcs1-0-0:basic_service_elements-general_http_request_rules-4 test fails with the following validation error:
   
cvc-complex-type.3.1: Value 'urn:ogc:def:crs:OGC:1.3:CRS84' of attribute 'srsName' of element 'lonLatEnvelope' is not valid with respect to the corresponding attribute use. Attribute 'srsName' has a fixed value of 'WGS84(DD)'.

However, the WCS 1.0.0 schemas published at "http://schemas.opengis.net/wcs/1.0.0/", as well as all of the archived versions (1.0.0.0, 1.0.0.1 and 1.0.0.2) published at "http://schemas.opengis.net/wcs/wcs-1_0_0.zip" all declare the following:

    <xs:attribute name="srsName" type="xs:anyURI" use="optional" fixed="urn:ogc:def:crs:OGC:1.3:CRS84"/>

which is exactly what the above WCS 1.0.0 service reports.  There exists no published WCS 1.0.0 schema that I can find (other than the in-document diagrams and Appendix) that fixes it to 'WGS84(DD)'.  Most OGC service specifications state "in the event of a discrepancy between bundled and schema repository versions of the XML Schema files, the schema repository shall be considered authoritative".  This rule makes sense, because it's the only way to allow services to serve valid XML.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by lgoltz** [comment]
There are currently two versions of the schemas in the ETS used:
 * the `original` with  `<xs:attribute name="srsName" type="xs:anyURI" fixed="WGS84(DD)"/>` and
 * `corrigendum1` with `<xs:attribute name="srsName" type="xs:anyURI" use="optional" fixed="urn:ogc:def:crs:OGC:1.3:CRS84"/>`

The user can choose between this two schemas on the main entry page of the test:
  * "The server implements the original schemas from the WCS 1.0.0 scpecification (OGC 03-065r6)"
  * "The server implements the schemas from the WCS 1.0.0 corrigendum (OGC 05-076)"

I think we should remove this possibility, remove the two schemas and replace them by the current version (1.0.0.3).
