### ISSUE TITLE
invalid XML character in getcoverage_operations-getcoverage_request-parameter-post-kvp-3

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs10#50]
SUT: http://ows.eox.at/cite/mapserver?service=wcs&version=1.0.0&request=getcapabilities

New HTML report could not be shown. Tomcat Log:
```
94d491> 			See the detail test Report /root/te_base/users/ogctest/s0001/log.xml
94d491> [Fatal Error] log.xml:108:32: An invalid XML character (Unicode: 0x8) was found in the element content of the document.
94d491> [Fatal Error] report_logs.xml:1:6510: Error attempting to parse XML file (href='/root/te_base/users/ogctest/s0001/d1e330_1/d1e1783_1/log.xml').
```

Similar to #45

**Comment by keshav-nangare** [comment]
> SUT: http://ows.eox.at/cite/mapserver?service=wcs&version=1.0.0&request=getcapabilities

Added fix of invalid character in XML. Tested successfully with above SUT.
