### ISSUE TITLE
HTML report is not filled with content with TEAM Engine v5.3

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs10#53]
Following setup is used:
- TEAM Engine v5.3
- ets-wcs10 v1.16
- IUT: http://ows.eox.at/cite/mapserver?service=wcs&version=1.0.0&request=getcapabilities

The HTML report is generated but there is no content (list of tests is missing).

If same setup is used with TEAM Engine v5.4, the HTML report is generated correctly.

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please try to find out why this problem is occurring with TEAM Engine v5.3 but not with v5.4 (e.g. find commit fixing the problem)?
Can you also check if this is a problem related to the particular test service (IUT) or if this is a general problem occurring with other test services as well?

**Comment by keshav-nangare** [comment]
@dstenger 

> Can you please try to find out why this problem is occurring with TEAM Engine v5.3 but not with v5.4 (e.g. find commit fixing the problem)?

I am able to reproduce the problem with TEAM Engine v5.3 and not with v5.4 as it was fixed in the https://github.com/opengeospatial/teamengine/pull/399 PR. 

 > Can you also check if this is a problem related to the particular test service (IUT) or if this is a general problem occurring with other test services as well?

This problem is not related to test service.
