### ISSUE TITLE
WCS 1.0.0 compliance test incorrectly reports my server has an invalid content type (te2 v1.18)

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs10#61]
these two tests are because of the same problem according to its log:
Test wcs1-0-0:getcoverage_operations-getcoverage_request-parameter-get-kvp-3
Test wcs1-0-0:getcoverage_operations-getcoverage_request-parameter-post-kvp-3

my server returns "application/vnd.ogc.se_xml" as content-type, however, the compliance test says it is an incorrect content-type:
![image](https://github.com/opengeospatial/ets-wcs10/assets/11200872/637f0bf1-37ac-409b-89e1-1b6cb9ff57e2)

it looks like "application/vnd.ogc.se_xml" should be a correct value according to 05-076_Web_Coverage_Service_WCS_Version_1.0.0_Corrigendum.pdf, page 10:
![image](https://github.com/opengeospatial/ets-wcs10/assets/11200872/a5b2f868-d1de-467f-977c-71756a2b200f)

testing service: http://34.207.80.206:6080/arcgis/services/mynetcdf_100/ImageServer/WCSServer

**Comment by dstenger** [comment]
@greatzzk Thank you for reporting. Did you test on the Production (https://cite.ogc.org/teamengine/) or Beta (https://cite.ogc.org/te2/) environment?
We will do further investigation.

Information for CITE team: It seems that following line has to be adjusted: https://github.com/opengeospatial/ets-wcs10/blob/82ad398e6af5472252401cfaefd480f88874c02f/src/main/scripts/ctl/wcs.xml#L6033
